name: flutter_sticky_group_list
description: "Flutter Sticky Group List, for creating sticky headers and group the list items."

version: 1.0.1

homepage: https://github.com/hamed-rezaee
repository: https://github.com/hamed-rezaee/flutter_sticky_group_list
issue_tracker: https://github.com/hamed-rezaee/flutter_sticky_group_list/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
